# Generated by Django 5.2.1 on 2025-05-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Betikma Hakkında', max_length=200, verbose_name='Sayfa Başlığı')),
                ('page_description', models.TextField(default='Yapay zeka gücüyle metinlerinizi dönüştüren, yaratıcı ve verimli bir platform.', verbose_name='Sayfa Açıklaması')),
                ('mission_title', models.CharField(default='Misyonumuz', max_length=100, verbose_name='Misyon Başlığı')),
                ('mission_text', models.TextField(default='Betikma olarak misyonumuz, yapay zekanın gücünü herkesin erişebileceği bir araç haline getirmek. Kullanıcılarımızın, metinlerini kolayca yeniden yazmalarına, geliştirmelerine ve yaratıcı potansiyellerini tam anlamıyla ortaya çıkarmalarına yardımcı oluyoruz. Dilin karmaşıklığını basitleştirerek, iletişimi daha etkili ve keyifli hale getirmeyi hedefliyoruz. Herkesin daha iyi metinler yazabilmesi için yenilikçi çözümler sunmaya, kullanıcı deneyimini sürekli iyileştirmeye ve yapay zeka teknolojilerini etik ve sorumlu bir şekilde kullanmaya kararlıyız.', verbose_name='Misyon Metni')),
                ('vision_title', models.CharField(default='Vizyonumuz', max_length=100, verbose_name='Vizyon Başlığı')),
                ('vision_text', models.TextField(default="Vizyonumuz, Betikma'yı küresel çapta lider bir AI metin editörü platformu haline getirmektir. İnsan ve yapay zeka iş birliğinin en iyi örneklerini sunarak, geleceğin iletişim standartlarını belirlemeyi amaçlıyoruz. Dil bariyerlerini ortadan kaldıran, yaratıcılığı teşvik eden ve her alanda metin üretimini kolaylaştıran bir dünya hayal ediyoruz. Sürekli öğrenen ve gelişen bir platform olarak, kullanıcılarımızın ihtiyaçlarına göre evrimleşmeyi ve onlara her zaman en güncel ve güçlü araçları sunmayı taahhüt ediyoruz.", verbose_name='Vizyon Metni')),
                ('value1_icon', models.CharField(default='fas fa-brain', max_length=50, verbose_name='Değer 1 İkonu (Font Awesome)')),
                ('value1_title', models.CharField(default='Yenilikçilik', max_length=100, verbose_name='Değer 1 Başlığı')),
                ('value1_description', models.TextField(default='Sürekli gelişen yapay zeka teknolojilerini takip eder, en yeni çözümleri sunarız.', verbose_name='Değer 1 Açıklaması')),
                ('value2_icon', models.CharField(default='fas fa-hands-helping', max_length=50, verbose_name='Değer 2 İkonu (Font Awesome)')),
                ('value2_title', models.CharField(default='Erişilebilirlik', max_length=100, verbose_name='Değer 2 Başlığı')),
                ('value2_description', models.TextField(default='Yapay zekayı herkesin kolayca kullanabileceği bir araç haline getiririz.', verbose_name='Değer 2 Açıklaması')),
                ('value3_icon', models.CharField(default='fas fa-shield-alt', max_length=50, verbose_name='Değer 3 İkonu (Font Awesome)')),
                ('value3_title', models.CharField(default='Güvenilirlik', max_length=100, verbose_name='Değer 3 Başlığı')),
                ('value3_description', models.TextField(default='Kullanıcı verilerinin gizliliğine ve güvenliğine en üst düzeyde önem veririz.', verbose_name='Değer 3 Açıklaması')),
            ],
            options={
                'verbose_name': 'Hakkımızda Sayfası İçeriği',
                'verbose_name_plural': 'Hakkımızda Sayfası İçerikleri',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('title', models.CharField(max_length=100, verbose_name='Unvan')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='team_members/', verbose_name='Profil Resmi')),
                ('placeholder_image_url', models.URLField(default='https://placehold.co/120x120/E8DCFF/7C3AED?text=PP', verbose_name="Placeholder Resim URL'si")),
            ],
            options={
                'verbose_name': 'Ekip Üyesi',
                'verbose_name_plural': 'Ekip Üyeleri',
            },
        ),
    ]
